# Generated by Django 4.1.3 on 2022-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karavanmodel',
            name='img1',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img10',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img2',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img3',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img4',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img5',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img6',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img7',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img8',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
        migrations.AlterField(
            model_name='karavanmodel',
            name='img9',
            field=models.ImageField(blank=True, upload_to='modeller', verbose_name='Karavan Resmi Ekle'),
        ),
    ]
