# Generated by Django 4.0.1 on 2022-11-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_karavanmodel_seodescription_karavanmodel_seotitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandevuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Adı Soyadı')),
                ('email', models.EmailField(max_length=254, verbose_name='Telefon Numarası')),
                ('telefon', models.IntegerField(verbose_name='telefon mumarası')),
                ('mesaj', models.TextField(verbose_name='Mesajınız')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Modelinizi Seçin')),
            ],
        ),
    ]
