# Generated by Django 4.0.1 on 2022-11-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_randevumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevumodel',
            name='servisneden',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
