# Generated by Django 4.1.3 on 2022-12-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_karavanmodel_agirlik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karavanmodel',
            old_name='Category',
            new_name='category',
        ),
    ]
