# Generated by Django 4.0.1 on 2022-12-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_category_karavanmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randevumodel',
            old_name='model',
            new_name='konu',
        ),
        migrations.RemoveField(
            model_name='randevumodel',
            name='servisneden',
        ),
    ]
