# Generated by Django 4.0.1 on 2022-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_model_randevumodel_konu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevumodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail '),
        ),
        migrations.AlterField(
            model_name='randevumodel',
            name='konu',
            field=models.CharField(max_length=150, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='randevumodel',
            name='telefon',
            field=models.IntegerField(verbose_name='Telefon mumarası'),
        ),
    ]
