# Generated by Django 4.1.3 on 2023-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_randevumodel_email_alter_randevumodel_konu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='yorum')),
                ('yorum', models.TextField()),
                ('unvan', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
