# Generated by Django 4.0.1 on 2022-11-09 19:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık Ekle')),
                ('img', models.ImageField(upload_to='blogs', verbose_name='Resim Ekle')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('description1', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Makele Detayı Yazın')),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
